#!/bin/bash
# set -e # exit if any command has non-zero return value
# set -u # exit if undefined reference found
# set -o pipefail # do not mask pipeline errors
# #set -x # debug mode
# IFS=$'\n\t'

git_sync() {
(
REMOTE="$1"
LOCALDIR="$(echo "$REMOTE" | rev | cut -d / -f 1 | rev)"

if [[ -d "$LOCALDIR" ]]; then
  (cd "$LOCALDIR" || exit 1; git pull)
else
  git clone "$REMOTE"
fi
)
}

PATH_PUSH_ONCE () {
if [[ ! "$PATH" =~ $1 ]]; then
  export PATH="$PATH:$1"
fi
}

