#!/bin/bash
# Stuff I use

# set -e # exit if any command has non-zero return value
# set -u # exit if undefined reference found
# set -o pipefail # do not mask pipeline errors
# #set -x # debug mode
# IFS=$'\n\t'

myk-update-db() {
find / >"$HOME/.myk-db" 2>/dev/null
# don't scan fat-c; don't care
#find / -not \( -path /fat-c -prune \) >$HOME/.myk-db 2>/dev/null
}

myk-find() {
if [ ! -f "$HOME/.myk-db" ]; then
  echo "Database not found; updating database..."
  myk-update-db
fi
grep --color=auto "$*" "$HOME/.myk-db"
}


myk-rnd-bg() {
feh --bg-fill --randomize ~/Downloads/*.jpg
}

myk-youtube-dl() {
youtube-dl --restrict-filenames -o '%(title)s.%(ext)s' "$@"
}

cs () {
# if cd succeeds, then ls
  cd "$@" && ls
}

install-debs () {
# install programs I like, on a Debian or Deb derivative (*buntu, Mint, etc)
# I guess this is closer to a posix sh-like way to solve this.
(

basic='build-essential
gdb git sudo curl tree
vim-gnome ctags
dos2unix mc links
tig
rename
shellcheck
tmux
markdown
atool
apt-transport-https
ca-certificates
software-properties-common'

desktop='fonts-symbola fonts-inconsolata
suckless-tools
youtube-dl
mpd mpc
mpv
feh
transmission-gtk
hexchat'

python='python3-pip python3-setuptools'

# we _do_ actually want word splitting here, so no quoted vars
sudo apt update && sudo apt upgrade && \
sudo apt install $basic $desktop $python \
--no-install-recommends && \
sudo apt autoremove && \
sudo apt autoclean && \
sudo apt clean
)
}

sapti () {
sudo apt update && sudo apt upgrade && \
sudo apt install "$*" && \
sudo apt-get autoremove && \
sudo apt-get autoclean && \
sudo apt-get clean
}

saptuu () {
sudo apt update && sudo apt upgrade && \
sudo apt-get autoremove && \
sudo apt-get autoclean && \
sudo apt-get clean
}
