#!/bin/bash
# installs the files

# set -e # exit if any command has non-zero return value
# set -u # exit if undefined reference found
# set -o pipefail # do not mask pipeline errors
# set -x # debug mode
# IFS=$'\n\t'

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

ensure_link () {
# Thanks slj!
	[[ -L "$2" ]] || ln -s "$1" "$2"
}

mkdir -p "$HOME/.vim/autoload" "$HOME/.vim/bundle"
mkdir -p "$HOME/.config/fontconfig"
mkdir -p "$HOME/.fluxbox/styles"
mkdir -p "$HOME/.vim"
mkdir -p "$HOME/bin"

install_dotfiles () {
(
dotdir="$HOME/dotfiles"
cd "$dotdir" || exit
ensure_link "$dotdir/Xresources" "$HOME/.Xresources"
ensure_link "$dotdir/xsessionrc" "$HOME/.xsessionrc"
ensure_link "$dotdir/bashrc" "$HOME/.bashrc"
ensure_link "$dotdir/emacs" "$HOME/.emacs"
ensure_link "$dotdir/fonts.conf" "$HOME/.config/fontconfig/fonts.conf"
ensure_link "$dotdir/functions" "$HOME/.functions"
ensure_link "$dotdir/inputrc" "$HOME/.inputrc"
ensure_link "$dotdir/irbrc" "$HOME/.irbrc"
ensure_link "$dotdir/profile" "$HOME/.profile"
ensure_link "$dotdir/pythonrc" "$HOME/.pythonrc"
ensure_link "$dotdir/tmux.conf" "$HOME/.tmux.conf"
ensure_link "$dotdir/toprc" "$HOME/.toprc"
ensure_link "$dotdir/vimrc" "$HOME/.vimrc"
)
}

install_vim() {
(
bundledir=$HOME/.vim/bundle

ensure_clone() {
# Wow, this is gross!
# Wow, this is cool.
#cd "$bundledir" || exit
git clone "$1" || ( cd "$2" && git pull "$1" )
# if clone fails
# subshell cd, etc
}


cd "$HOME/.vim" || exit
ensure_clone 'https://github.com/tpope/vim-pathogen' 'vim-pathogen'
ensure_link "$HOME/.vim/vim-pathogen/autoload/pathogen.vim" \
	"$HOME/.vim/autoload/pathogen.vim"

cd "$bundledir" || exit
ensure_clone "https://github.com/vim-syntastic/syntastic" "syntastic"
ensure_clone "https://github.com/tpope/vim-fugitive" "vim-fugitive"
ensure_clone "https://github.com/tpope/vim-sleuth" "vim-sleuth"
ensure_clone "https://github.com/sjl/badwolf" "badwolf"
ensure_clone "https://github.com/jceb/vim-orgmode" "vim-orgmode"
ensure_clone "https://github.com/tpope/vim-speeddating" "vim-speeddating"
ensure_clone "https://github.com/scrooloose/nerdtree" "nerdtree"
ensure_clone "https://github.com/kien/ctrlp.vim" "ctrlp.vim"
ensure_clone "https://github.com/kien/rainbow_parentheses.vim" "rainbow_parentheses.vim"
ensure_clone "https://github.com/fatih/vim-go" "vim-go"
)
}

install_debs() {

(

basic='build-essential
gdb git sudo curl tree
vim-gnome ctags
dos2unix mc links
tig
rename
shellcheck
tmux
markdown
atool
apt-transport-https
ca-certificates
software-properties-common'

desktop='fonts-symbola fonts-inconsolata
suckless-tools
youtube-dl
mpv
feh
transmission-gtk
hexchat'

python='python3-pip python3-setuptools'

# we _do_ actually want word splitting here, so no quoted vars
sudo apt update && sudo apt upgrade && \
sudo apt install $basic $desktop $python \
--no-install-recommends && \
sudo apt autoremove && \
sudo apt autoclean && \
sudo apt clean
)
}

install_fluxbox()
{
(
dotdir="$HOME/dotfiles"
ensure_link "$dotdir/fluxbox/init" "$HOME/.fluxbox/init"
ensure_link "$dotdir/fluxbox/keys" "$HOME/.fluxbox/keys"
ensure_link "$dotdir/fluxbox/menu" "$HOME/.fluxbox/menu"
python "$dotdir/fluxbox/themer" '906090' > "$dotdir/fluxbox/styles/theme"
)
}

main() {
install_dotfiles
install_vim
install_fluxbox
}

main
