#!/bin/sh
# I use these packages on Debian

(
basic='
apt-transport-https
atool
build-essential
ca-certificates
ctags
dos2unix
emacs
gdb
markdown
shellcheck
software-properties-common
tree
vim-gtk3
'

desktop='
fonts-symbola
hexchat
transmission-gtk
'

python='python3-venv python3-pip python3-setuptools'

# we _do_ actually want word splitting here, so no quoted vars
sudo apt update && sudo apt upgrade && \
sudo apt install $basic $desktop $python \
--no-install-recommends && \
sudo apt autoremove && \
sudo apt autoclean && \
sudo apt clean
)
