#!/bin/bash
# installs the files

# set -x # debug mode

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

git_sync() {
(
REMOTE="$1"
LOCALDIR="$(echo "$REMOTE" | cut -d'/' -f5)"

if [[ -d "$LOCALDIR" ]]; then
  (cd "$LOCALDIR"; git pull)
else
  git clone "$REMOTE"
fi
)
}

mkdir -p "$HOME/.vim/autoload" "$HOME/.vim/bundle"
mkdir -p "$HOME/.config/fontconfig"
mkdir -p "$HOME/.vim"
mkdir -p "$HOME/bin"

install_dotfiles () {
(
dotdir="$HOME/dotfiles"
cd "$dotdir" || die
ln -sf "$dotdir/Xresources" "$HOME/.Xresources"
ln -sf "$dotdir/xsessionrc" "$HOME/.xsessionrc"
ln -sf "$dotdir/bashrc" "$HOME/.bashrc"
ln -sf "$dotdir/emacs" "$HOME/.emacs"
ln -sf "$dotdir/fonts.conf" "$HOME/.config/fontconfig/fonts.conf"
ln -sf "$dotdir/functions" "$HOME/.functions"
ln -sf "$dotdir/inputrc" "$HOME/.inputrc"
ln -sf "$dotdir/irbrc" "$HOME/.irbrc"
ln -sf "$dotdir/profile" "$HOME/.profile"
ln -sf "$dotdir/pythonrc" "$HOME/.pythonrc"
ln -sf "$dotdir/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$dotdir/vimrc" "$HOME/.vimrc"
)
}

install_vim() {
(
bundledir=$HOME/.vim/bundle

cd "$HOME/.vim" || die
git_sync "https://github.com/tpope/vim-pathogen"
ln -sf "$HOME/.vim/vim-pathogen/autoload/pathogen.vim" \
	"$HOME/.vim/autoload/pathogen.vim"

cd "$bundledir" || die
git_sync "https://github.com/vim-syntastic/syntastic"
git_sync "https://github.com/tpope/vim-fugitive"
git_sync "https://github.com/tpope/vim-sleuth"
git_sync "https://github.com/sjl/badwolf"
git_sync "https://github.com/jceb/vim-orgmode"
git_sync "https://github.com/tpope/vim-speeddating"
git_sync "https://github.com/scrooloose/nerdtree"
git_sync "https://github.com/kien/ctrlp.vim"
git_sync "https://github.com/kien/rainbow_parentheses.vim"
git_sync "https://github.com/fatih/vim-go"
)
}

main() {
install_dotfiles
install_vim
}

main
