#!/bin/bash

set -e

mkdir -p "$HOME/.config/openbox"
mkdir -p "$HOME/.config/conky"

(
dotdir="$HOME/dotfiles"
cd "$dotdir"
ln -sf "$dotdir/ob-autostart" "$HOME/.config/openbox/autostart"
ln -sf "$dotdir/rc.xml" "$HOME/.config/openbox/rc.xml"
ln -sf "$dotdir/conky.conf" "$HOME/.config/conky/conky.conf"
ln -sf "$dotdir/compton.conf" "$HOME/.config/compton.conf"
)
