#!/bin/bash
# I use these packages on Debian

(
basic='
apt-transport-https
atool
build-essential
ca-certificates
ctags
curl
dos2unix
gdb
git
links
markdown
rename
shellcheck
software-properties-common
sudo
tig
tmux
tree
vim-gtk3
'

desktop='
compton
conky
feh
fonts-inconsolata
fonts-symbola
hexchat
nitrogen
openbox
pasystray
suckless-tools
tint2
transmission-gtk
'

python='python3-venv python3-pip python3-setuptools'

# we _do_ actually want word splitting here, so no quoted vars
sudo apt update && sudo apt upgrade && \
sudo apt install $basic $desktop $python \
--no-install-recommends && \
sudo apt autoremove && \
sudo apt autoclean && \
sudo apt clean
)
