#!/bin/sh
# I use these on Fedora

(
desktop='
keepassx
perl-Text-Markdown
sbcl
vim
'

dev='
@development-tools
fedora-packager
rpmdevtools
'
#ShellCheck

sudo dnf update && sudo dnf upgrade && \
sudo dnf install $desktop #$dev
)

