#!/usr/bin/env perl

use v5.18;
use warnings;
use autodie;

use feature 'say';

use File::Path qw(make_path);
use File::Basename qw(basename dirname);

exit main(@ARGV);

sub main {
	my ($source,$destination) = @_;

	die "Bad source file path: $source\n" unless -e $source;

	my $destination_parent = dirname($destination);

	if (-e $destination_parent) {
		say "Directory already exists: " . $destination_parent;
	} else {
		die "make_path fail" unless make_path($destination_parent);
	}

	if (-l $destination) {
		die "Symbolic link already exists: $destination\n";
	} else {
		die "Symlink fail" unless symlink($source,$destination);
	}
	return 0;
}
