#!/usr/bin/env python3

import os
import sys
from pathlib import Path

assert(len(sys.argv) == 3)

try:
    os.makedirs(Path(sys.argv[2]).parent)
except OSError as e:
    if e.errno == 17:
        pass
        #print("File exists: {}".format(sys.argv[2]))
    else:
        print(e)

try:
    os.symlink(sys.argv[1], sys.argv[2])
except OSError as e:
    if e.errno == 17:
        pass
        #print("Symlink exists: {}".format(sys.argv[2]))
    else:
        print(e)
