#!/usr/bin/env bash
# installs debian packages from the list in debs

set -e # exit if any command has non-zero return value
set -u # exit if undefined reference found
set -o pipefail # do not mask pipeline errors
#set -x # debug mode 
#IFS=$'\n\t'

sudo apt update && \
sudo apt upgrade && \
sudo apt install $(sed -e 's/#.*$//g' debs | tr '\n' ' ')
