#!/bin/sh
# install programs I like, on a Debian or Deb derivative (*buntu, Mint, etc)

basics='
build-essential
gdb git sudo curl tree htop
vim-gnome ctags vim-syntastic vim-pathogen
dos2unix mc links
tig
rename stow
shellcheck
tmux
markdown 
atool
fonts-symbola fonts-inconsolata
suckless-tools
youtube-dl
mpd mpc
'

desktop='
mpv
feh 
transmission-gtk
hexchat'

python='python3-pip'

#echo "$basics $desktop $python"

sudo apt update && \
sudo apt upgrade && \
sudo apt install \
"$basics" \
"$desktop" \
"$python" \
--no-install-recommends

sudo apt autoremove
sudo apt autoclean
sudo apt clean
