#!/usr/bin/env bash

#set -e # exit if any command has non-zero return value
#set -u # exit if undefined reference found
#set -o pipefail # do not mask pipeline errors
#set -x # debug mode 
#IFS=$'\n\t'

#shout() { echo "$0: $*" >&2; }
#barf() { shout "fatal: $*"; exit 111; }
#safe() { "$@" || barf "cannot $*"; }
#quiet() { "$@" > /dev/null 2>&1; }
#die() {
#  printf '%s\n' "$1" >&2
#  exit 1
#}
