#!/usr/bin/env python3

import os
import subprocess
import sys

os.chdir(sys.argv[1])

try:
    subprocess.run(["git", "clone", sys.argv[2]], check=True, stderr=subprocess.DEVNULL)
except subprocess.CalledProcessError as e:

    if e.returncode == 128:

        git_directory = sys.argv[2].split('/')[-1:][0]

        os.chdir(git_directory)
        subprocess.run(["git", "pull", "--quiet"], check=True)
    else:
        print(e)
